#!/bin/sh

#generate docs and add to index
echo "pre-commit:\tGenerating documentation"
coffeedoc --renderer gfm --hide-private lib/*
git add docs/

cat README-base.md docs/Lib* CHANGELOG.md LICENSE.md > README.md
git add README.md

#compile sources and tests
mkdir -p js/test
mkdir -p js/lib
coffee -cl *.coffee lib/*.coffee
coffee -cl -o js *.coffee
coffee -cl -o js/test test/*.coffee
coffee -cl -o js/lib lib/*.coffee
git add -f js/*.js
git add -f js/test/*.js
git add -f js/lib/*.js

#run tests, stop commit if they fail!
npm test
RET_VAL=$?
travis-lint
RET_VAL=$(($RET_VAL + $?))
exit $RET_VAL
