#!/bin/sh

#generate docs and add to index
echo "pre-commit:\tGenerating documentation"
coffeedoc --renderer gfm --hide-private lib/*
git add docs/

cat README-base.md docs/Lib* CHANGELOG.md LICENSE.md > README.md
git add README.md

#compile sources and tests
coffee -cl *.coffee */*.coffee
git add -f tests/*.js

#run tests, stop commit if they fail!
npm test
RET_VAL=$?
travis-lint
RET_VAL=$(($RET_VAL + $?))
exit $RET_VAL
